[package]
name = "hir_ty"
version = "0.1.0"
edition = "2021"

[dependencies]
base_db.workspace = true
hir_def.workspace = true
salsa.workspace = true
indexmap.workspace = true

[lints]
workspace = true